
package com.pmrodrigues.sms.mobipronto.webservice;

import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 */
@WebServiceClient(name = "MPGateway", targetNamespace = "MobileProntoMPGateway", wsdlLocation = "file:/C:/Users/Marceloo/workspace/com.pmrodrigues/sms/src/test/resources/wsdl/mpgateway.wsdl")
public class MPGateway
        extends Service {

    private final static URL MPGATEWAY_WSDL_LOCATION;
    private final static WebServiceException MPGATEWAY_EXCEPTION;
    private final static QName MPGATEWAY_QNAME = new QName("MobileProntoMPGateway", "MPGateway");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://www.mpgateway.com/v_3_00/sms/service.asmx?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MPGATEWAY_WSDL_LOCATION = url;
        MPGATEWAY_EXCEPTION = e;
    }

    public MPGateway() {
        super(__getWsdlLocation(), MPGATEWAY_QNAME);
    }

    public MPGateway(WebServiceFeature... features) {
        super(__getWsdlLocation(), MPGATEWAY_QNAME, features);
    }

    public MPGateway(URL wsdlLocation) {
        super(wsdlLocation, MPGATEWAY_QNAME);
    }

    public MPGateway(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, MPGATEWAY_QNAME, features);
    }

    public MPGateway(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MPGateway(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * @return returns MPGatewaySoap
     */
    @WebEndpoint(name = "MPGatewaySoap")
    public MPGatewaySoap getMPGatewaySoap() {
        return super.getPort(new QName("MobileProntoMPGateway", "MPGatewaySoap"), MPGatewaySoap.class);
    }

    /**
     * @param features A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return returns MPGatewaySoap
     */
    @WebEndpoint(name = "MPGatewaySoap")
    public MPGatewaySoap getMPGatewaySoap(WebServiceFeature... features) {
        return super.getPort(new QName("MobileProntoMPGateway", "MPGatewaySoap"), MPGatewaySoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (MPGATEWAY_EXCEPTION != null) {
            throw MPGATEWAY_EXCEPTION;
        }
        return MPGATEWAY_WSDL_LOCATION;
    }

}
