
package com.pmrodrigues.sms.mobipronto.webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import java.math.BigDecimal;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 */
@WebService(name = "MPGatewaySoap", targetNamespace = "MobileProntoMPGateway")
@XmlSeeAlso({
        ObjectFactory.class
})
public interface MPGatewaySoap {

    @WebMethod(operationName = "MPG_Calculate_Message_Length_UTF8_or_UTF16", action = "MobileProntoMPGateway/MPG_Calculate_Message_Length_UTF8_or_UTF16")
    @WebResult(name = "MPG_Calculate_Message_Length_UTF8_or_UTF16Result", targetNamespace = "MobileProntoMPGateway")
    @RequestWrapper(localName = "MPG_Calculate_Message_Length_UTF8_or_UTF16", targetNamespace = "MobileProntoMPGateway", className = "MPGCalculateMessageLengthUTF8OrUTF16")
    @ResponseWrapper(localName = "MPG_Calculate_Message_Length_UTF8_or_UTF16Response", targetNamespace = "MobileProntoMPGateway", className = "MPGCalculateMessageLengthUTF8OrUTF16Response")
    public int mpgCalculateMessageLengthUTF8OrUTF16(
            @WebParam(name = "Credencial", targetNamespace = "MobileProntoMPGateway")
            String credencial,
            @WebParam(name = "Token", targetNamespace = "MobileProntoMPGateway")
            String token,
            @WebParam(name = "Message", targetNamespace = "MobileProntoMPGateway")
            String message);


    @WebMethod(operationName = "MPG_SendSimple_SMS", action = "MobileProntoMPGateway/MPG_SendSimple_SMS")
    @WebResult(name = "MPG_SendSimple_SMSResult", targetNamespace = "MobileProntoMPGateway")
    @RequestWrapper(localName = "MPG_SendSimple_SMS", targetNamespace = "MobileProntoMPGateway", className = "MPGSendSimpleSMS")
    @ResponseWrapper(localName = "MPG_SendSimple_SMSResponse", targetNamespace = "MobileProntoMPGateway", className = "MPGSendSimpleSMSResponse")
    public String mpgSendSimpleSMS(
            @WebParam(name = "Credencial", targetNamespace = "MobileProntoMPGateway")
            String credencial,
            @WebParam(name = "Token", targetNamespace = "MobileProntoMPGateway")
            String token,
            @WebParam(name = "Mobile", targetNamespace = "MobileProntoMPGateway")
            String mobile,
            @WebParam(name = "Message", targetNamespace = "MobileProntoMPGateway")
            String message);

    @WebMethod(operationName = "MPG_SendandFollowUp_SMS", action = "MobileProntoMPGateway/MPG_SendandFollowUp_SMS")
    @WebResult(name = "MPG_SendandFollowUp_SMSResult", targetNamespace = "MobileProntoMPGateway")
    @RequestWrapper(localName = "MPG_SendandFollowUp_SMS", targetNamespace = "MobileProntoMPGateway", className = "MPGSendandFollowUpSMS")
    @ResponseWrapper(localName = "MPG_SendandFollowUp_SMSResponse", targetNamespace = "MobileProntoMPGateway", className = "MPGSendandFollowUpSMSResponse")
    public String mpgSendandFollowUpSMS(
            @WebParam(name = "Credencial", targetNamespace = "MobileProntoMPGateway")
            String credencial,
            @WebParam(name = "Token", targetNamespace = "MobileProntoMPGateway")
            String token,
            @WebParam(name = "Principal_User", targetNamespace = "MobileProntoMPGateway")
            String principalUser,
            @WebParam(name = "Aux_User", targetNamespace = "MobileProntoMPGateway")
            String auxUser,
            @WebParam(name = "Mobile", targetNamespace = "MobileProntoMPGateway")
            String mobile,
            @WebParam(name = "Send_Project", targetNamespace = "MobileProntoMPGateway")
            String sendProject,
            @WebParam(name = "Message", targetNamespace = "MobileProntoMPGateway")
            String message);


    @WebMethod(operationName = "MPG_Send_SMS", action = "MobileProntoMPGateway/MPG_Send_SMS")
    @WebResult(name = "MPG_Send_SMSResult", targetNamespace = "MobileProntoMPGateway")
    @RequestWrapper(localName = "MPG_Send_SMS", targetNamespace = "MobileProntoMPGateway", className = "MPGSendSMS")
    @ResponseWrapper(localName = "MPG_Send_SMSResponse", targetNamespace = "MobileProntoMPGateway", className = "MPGSendSMSResponse")
    public String mpgSendSMS(
            @WebParam(name = "Credencial", targetNamespace = "MobileProntoMPGateway")
            String credencial,
            @WebParam(name = "Token", targetNamespace = "MobileProntoMPGateway")
            String token,
            @WebParam(name = "Principal_User", targetNamespace = "MobileProntoMPGateway")
            String principalUser,
            @WebParam(name = "Aux_User", targetNamespace = "MobileProntoMPGateway")
            String auxUser,
            @WebParam(name = "Mobile", targetNamespace = "MobileProntoMPGateway")
            String mobile,
            @WebParam(name = "Send_Project", targetNamespace = "MobileProntoMPGateway")
            String sendProject,
            @WebParam(name = "Message", targetNamespace = "MobileProntoMPGateway")
            String message);

    @WebMethod(operationName = "MPG_Credits", action = "MobileProntoMPGateway/MPG_Credits")
    @RequestWrapper(localName = "MPG_Credits", targetNamespace = "MobileProntoMPGateway", className = "MPGCredits")
    @ResponseWrapper(localName = "MPG_CreditsResponse", targetNamespace = "MobileProntoMPGateway", className = "MPGCreditsResponse")
    public void mpgCredits(
            @WebParam(name = "Credencial", targetNamespace = "MobileProntoMPGateway")
            String credencial,
            @WebParam(name = "Token", targetNamespace = "MobileProntoMPGateway")
            String token,
            @WebParam(name = "v_st_Status", targetNamespace = "MobileProntoMPGateway", mode = WebParam.Mode.INOUT)
            Holder<String> vStStatus,
            @WebParam(name = "MPG_CreditsResult", targetNamespace = "MobileProntoMPGateway", mode = WebParam.Mode.OUT)
            Holder<BigDecimal> mpgCreditsResult);

    @WebMethod(operationName = "MPG_Send_LMS", action = "MobileProntoMPGateway/MPG_Send_LMS")
    @WebResult(name = "MPG_Send_LMSResult", targetNamespace = "MobileProntoMPGateway")
    @RequestWrapper(localName = "MPG_Send_LMS", targetNamespace = "MobileProntoMPGateway", className = "MPGSendLMS")
    @ResponseWrapper(localName = "MPG_Send_LMSResponse", targetNamespace = "MobileProntoMPGateway", className = "MPGSendLMSResponse")
    public String mpgSendLMS(
            @WebParam(name = "Credencial", targetNamespace = "MobileProntoMPGateway")
            String credencial,
            @WebParam(name = "Token", targetNamespace = "MobileProntoMPGateway")
            String token,
            @WebParam(name = "Principal_User", targetNamespace = "MobileProntoMPGateway")
            String principalUser,
            @WebParam(name = "Aux_User", targetNamespace = "MobileProntoMPGateway")
            String auxUser,
            @WebParam(name = "Mobile", targetNamespace = "MobileProntoMPGateway")
            String mobile,
            @WebParam(name = "Message", targetNamespace = "MobileProntoMPGateway")
            String message);

    @WebMethod(operationName = "MPG_Send_Long_SMS", action = "MobileProntoMPGateway/MPG_Send_Long_SMS")
    @WebResult(name = "MPG_Send_Long_SMSResult", targetNamespace = "MobileProntoMPGateway")
    @RequestWrapper(localName = "MPG_Send_Long_SMS", targetNamespace = "MobileProntoMPGateway", className = "MPGSendLongSMS")
    @ResponseWrapper(localName = "MPG_Send_Long_SMSResponse", targetNamespace = "MobileProntoMPGateway", className = "MPGSendLongSMSResponse")
    public String mpgSendLongSMS(
            @WebParam(name = "Credencial", targetNamespace = "MobileProntoMPGateway")
            String credencial,
            @WebParam(name = "Token", targetNamespace = "MobileProntoMPGateway")
            String token,
            @WebParam(name = "Principal_User", targetNamespace = "MobileProntoMPGateway")
            String principalUser,
            @WebParam(name = "Aux_User", targetNamespace = "MobileProntoMPGateway")
            String auxUser,
            @WebParam(name = "Mobile", targetNamespace = "MobileProntoMPGateway")
            String mobile,
            @WebParam(name = "Message", targetNamespace = "MobileProntoMPGateway")
            String message);

}
