CREATE TABLE modalidade (
  id     BIGINT       NOT NULL AUTO_INCREMENT,
  codigo CHAR(4)      NOT NULL,
  nome   VARCHAR(100) NOT NULL,
  PRIMARY KEY (id)
);

INSERT INTO MODALIDADE (codigo, nome) VALUES ('0001', 'PADRÃO');

ALTER TABLE operadora
ADD COLUMN modalidade_id BIGINT NULL,
ADD COLUMN codigo CHAR(4) NULL,
ADD COLUMN qualicorp BOOLEAN NULL DEFAULT FALSE,
ADD COLUMN usaPrimeiraParcela BOOLEAN NULL DEFAULT FALSE,
ADD COLUMN excluido BOOLEAN NULL DEFAULT FALSE,
ADD COLUMN quantidadeParcelas INT NULL;

ALTER TABLE operadora
ADD CONSTRAINT FK_MODALIDADE_OPERADORA FOREIGN KEY (modalidade_id) REFERENCES modalidade (id);

ALTER TABLE operadora
ADD COLUMN administradora_id BIGINT NULL;

ALTER TABLE operadora
ADD CONSTRAINT FK_ADMINISTRADORA_OPERADORA FOREIGN KEY (administradora_id) REFERENCES cedente (id);
